name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
      - name: Run tests
        run: mvn test
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
      - name: Build the project
        run: mvn package
      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/

  notify:
    runs-on: ubuntu-latest
    needs: test  # Rodará em paralelo com 'build'
    steps:
      - uses: actions/checkout@v3
      - name: Install sendmail
        run: sudo apt-get install -y sendmail
      - name: Run email notification script
        env:
          EMAIL_TO_NOTIFY: ${{ secrets.EMAIL_TO_NOTIFY }}
        run: |
          chmod +x ./send_email.sh
          ./send_email.sh $EMAIL_TO_NOTIFY

  notifyPy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install Python SMTP libraries
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip
          pip3 install secure-smtplib
      - name: Run email notification script
        env:
          EMAIL_TO_NOTIFY: ${{ secrets.EMAIL_TO_NOTIFY }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python3 ./send_email.py