name: Java CI Pipeline

# Quando o pipeline deve ser acionado
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Definição de jobs
jobs:
  # Job 1: Executar os testes
  test:
    runs-on: ubuntu-latest
    steps:
      # Checar o código do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # Configurar o JDK
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'corretto' # Pode ser alterado para o seu JDK preferido

      # Instalar dependências
      - name: Install dependencies
        run: mvn install -DskipTests

      # Executar testes
      - name: Run tests
        run: mvn test

      # Salvar resultados dos testes como artefato
      - name: Save test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/

  # Job 2: Build do projeto
  build:
    runs-on: ubuntu-latest
    needs: test  # Esse job só roda após o job de testes
    steps:
      # Checar o código do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # Configurar o JDK
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'corretto'

      # Executar o build
      - name: Build project
        run: mvn package

      # Salvar o pacote gerado como artefato
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-package
          path: target/*.jar
